version: 2
updates:
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "daily"
  labels:
    - "dependencies"
- package-ecosystem: "gomod"
  directory: "/cmd/vulcan-build-images/testdata/"
  schedule:
    interval: "daily"
  ignore:
  - dependency-name: "github.com/aws/aws-sdk-go"
    update-types: ["version-update:semver-patch"]
  labels:
    - "dependencies"
- package-ecosystem: "docker"
  directory: "/cmd/vulcan-build-images/testdata/testcheck/"
  schedule:
    interval: "weekly"
  labels:
    - "dependencies"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  labels:
    - "dependencies"
