language: go
dist: trusty
go:
  - 1.13.3
env:
  global:
    - IMAGES_TO_BUILD_PATH=/tmp/images
    - CGO_ENABLED=0
    - DOCKER_API_VERSION=1.23
go_import_path: github.com/adevinta/vulcan-checks-bsys
install: sh ./_script/confdocker
script:
  - go test -short
