language: go
dist: bionic
services:
  - docker
go:
  - 1.18.x
env:
  global:
    - IMAGES_TO_BUILD_PATH=/tmp/images
    - CGO_ENABLED=0
    - DOCKER_API_VERSION=1.23
go_import_path: github.com/adevinta/vulcan-checks-bsys
script:
  - go get ./cmd/vulcan-build-images/testdata/testcheck
  - go test -short ./...
